#!/usr/bin/env python3
"""Generate the encrypted, built-in KeeLoq manufacturer keystore header.

The plaintext keystore (one `name;key_hex;type` entry per line) is the source
of truth and is kept OUT of the repository (default: .idea/mfcodes, which is
gitignored). This script encrypts it with AES-256-CBC and emits a C header with
the key, IV and ciphertext, which IS committed. At runtime the firmware decrypts
this blob as a fallback when no external /mfcodes file is present.

Encryption is obfuscation, not real security: the AES key ships in the binary.
The goal is simply to keep the plaintext manufacturer keys out of the git repo
and out of `strings firmware.bin`, mirroring how Flipper-like firmwares ship
their keystore. Re-run this script (rotating the key/IV) whenever the plaintext
keystore changes.

Requirements: `openssl` in PATH (Git for Windows ships it). Pure stdlib otherwise.

Usage:
    python tools/gen_mfcodes.py [plaintext_path] [header_path]
"""
import os
import subprocess
import sys
import tempfile

DEFAULT_PLAIN = ".idea/mfcodes"
DEFAULT_HEADER = "src/modules/rf/protocols/rf_keeloq_mfcodes_data.h"


def normalize(plaintext_path):
    """Read the plaintext keystore and keep only valid `name;key;type` lines."""
    lines = []
    with open(plaintext_path, "r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if not line:
                continue
            cols = line.split(";")
            if len(cols) != 3:
                print(f"  skipping malformed line: {line!r}", file=sys.stderr)
                continue
            lines.append(";".join(c.strip() for c in cols))
    if not lines:
        sys.exit("error: no valid entries in plaintext keystore")
    # Trailing newline so the C parser sees the last entry cleanly.
    return ("\n".join(lines) + "\n").encode("utf-8")


def openssl_cbc(data, key, iv, decrypt=False):
    """Run AES-256-CBC (PKCS7) through the openssl CLI, return the result bytes."""
    with tempfile.TemporaryDirectory() as d:
        src = os.path.join(d, "in.bin")
        dst = os.path.join(d, "out.bin")
        with open(src, "wb") as f:
            f.write(data)
        cmd = [
            "openssl", "enc", "-aes-256-cbc",
            "-K", key.hex(), "-iv", iv.hex(),
            "-in", src, "-out", dst,
        ]
        if decrypt:
            cmd.append("-d")
        subprocess.run(cmd, check=True)
        with open(dst, "rb") as f:
            return f.read()


def c_array(name, data, ctype="uint8_t"):
    body = []
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i:i + 12])
        body.append("    " + chunk + ",")
    return f"static const {ctype} {name}[] = {{\n" + "\n".join(body) + "\n};\n"


def main():
    plain_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_PLAIN
    header_path = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_HEADER

    if not os.path.exists(plain_path):
        sys.exit(
            f"error: plaintext keystore not found: {plain_path}\n"
            "Provide it as the first argument or place it at .idea/mfcodes."
        )

    plaintext = normalize(plain_path)
    key = os.urandom(32)
    iv = os.urandom(16)

    ciphertext = openssl_cbc(plaintext, key, iv)

    # Self-check: decrypt back and compare, so a committed header is never wrong.
    roundtrip = openssl_cbc(ciphertext, key, iv, decrypt=True)
    if roundtrip != plaintext:
        sys.exit("error: AES round-trip self-check failed")

    header = (
        "#pragma once\n"
        "#include <stdint.h>\n\n"
        "// Auto-generated by tools/gen_mfcodes.py - DO NOT EDIT.\n"
        "// Encrypted KeeLoq manufacturer keystore (AES-256-CBC, PKCS7).\n"
        "// Plaintext source is kept out of the repo; re-run the generator to\n"
        "// rotate the key/IV and refresh this blob after changing the keystore.\n\n"
        + c_array("KEELOQ_MFCODES_KEY", key)
        + "\n"
        + c_array("KEELOQ_MFCODES_IV", iv)
        + "\n"
        + c_array("KEELOQ_MFCODES_ENC", ciphertext)
        + f"\nstatic const uint32_t KEELOQ_MFCODES_ENC_LEN = {len(ciphertext)};\n"
    )

    os.makedirs(os.path.dirname(header_path), exist_ok=True)
    with open(header_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)

    entries = plaintext.decode("utf-8").count("\n")
    print(f"wrote {header_path}: {entries} entries, "
          f"{len(plaintext)} B plaintext -> {len(ciphertext)} B ciphertext")


if __name__ == "__main__":
    main()
