---
name: Build and Push OR check-PR

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
        - "**.yml"
        - "**.h"
        - "**.cpp"
        - "**.py"
        - "**.html"
        - "**.css"
        - "**.js"
        - "**.ini"
        - "**.json"
        - "**.csv"

  workflow_dispatch:

jobs:
  compile_sketch:
    name: Build ${{ matrix.board.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - {
              name: "ESP32-S3 - M5Cardputer",
              env: "m5stack-cardputer",
              partitions: { bootloader_addr: "0x0000" },
            }
          - {
              name: "ESP32 - M5StickCPlus2",
              env: "m5stack-cplus2",
              partitions: { bootloader_addr: "0x1000" },
            }
          - {
              name: "Headless: ESP32-S3",
              env: "esp32-s3-devkitc-1",
              partitions: { bootloader_addr: "0x0" },
            }
          - {
              name: "CoreS3",
              env: "m5stack-cores3",
              partitions: { bootloader_addr: "0x0" },
            }
          - {
              name: "Launcher based environment: CYD",
              env: "LAUNCHER_CYD-2432S028",
              partitions: { bootloader_addr: "0x1000" },
            }
          - {
              name: "ESP32-C5",
              env: "nm-cyd-c5",
              partitions: { bootloader_addr: "0x2000" },
            }
          - {
              name: "ESP32-C6",
              env: "arduino-nesso-n1",
              partitions: { bootloader_addr: "0x2000" },
            }
    steps:
      - uses: actions/checkout@v4

      - id: build
        name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install build deps (multilib)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gcc-multilib libc6-dev-i386

      - name: Install PlatformIO Core
        run: |
          pip install platformio requests esptool intelhex

          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            version=${{ github.ref_name }}
          else
            version="${GITHUB_SHA::7}"
          fi

          sed -i "s/-DBRUCE_VERSION=/-DBRUCE_VERSION='\"$version\"' ; /g" ./platformio.ini
          sed -i "s/-DGIT_COMMIT_HASH='\"Homebrew\"'/\!echo '-DGIT_COMMIT_HASH=\\\\\\\\\"'\$\(git describe --always --dirty)'\\\\\\\\\"'/g" ./platformio.ini

          cat ./platformio.ini

      - name: Run Compile
        run: |
          platformio run -e ${{ matrix.board.env }}

      - name: Upload ${{ matrix.board.name }}
        uses: actions/upload-artifact@v4
        with:
          name: Bruce-${{ matrix.board.env }}
          path: Bruce-*.bin
          retention-days: 5
          if-no-files-found: error
